### PR TITLE
Update the changelog.md

### PR DESCRIPTION
**Pull request by josemasensio**
Dear @MarcoMinghini,

We have aligned the 'helpdesk' branch to the 'master' branch and then, we have made the following changes:

- The version 'v1.0.4' has been added in 'Staging' section.

- The version 'v1.0.3' has been modified.

Best regards.

### CODE REVIEW

**Comment by MarcoMinghini** [comment]
Fine.

Just a couple of comments:
- if a change is already deployed (in staging or in production), no need to reference the pull request. I see that this is not done in the changelog for the previous Modifications.
- I propose to include the link to the issue in the title, and not in the bullet list (just to make the whole text shorter). This change should be done to all the other Modifications (let's do it separately - I can also commit to do that).

I will merge the PR and manually make the first change.

**Comment by josemasensio** [comment]
@MarcoMinghini thank you for your feedback. We have made the changes manually in the 'master' and 'helpdesk' branches. 

Could you review them and tell us if they are correct?

**Comment by MarcoMinghini** [comment]
Yes, they are fine, thansk.

In the 'master' branch I manually added the issue #257 (in the ets repo) which is the same as the issue #5 (in the community repo). This specific solution has been already tested and approved, do you think we can move it in production also? We can schedule it (together with others, depending on the tests from the reporters) for the moment when the new cloud instance will be officially presented. What do you think?

**Comment by josemasensio** [comment]
@MarcoMinghini fine! We think that this change can move to production when the new cloud instance is presented. In reference to the issue #257, we are going to add it manually to the 'helpdesk' branch.

**Pull request merged**
